version: "3.8"

services:
  backend:
    build:
      context: ./Core
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FAL_API_KEY=${FAL_API_KEY}
      - DATABASE_URL=sqlite:///./jobs.db
      - ALLOWED_ORIGINS=http://localhost:3000
    volumes:
      - ./Core:/app
      - ./Core/uploads:/app/uploads
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./Web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
